/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flpCrowdsaleSol from "./FLPCrowdsale.sol";
export type { flpCrowdsaleSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { USDT } from "./USDT";
